# Generated by Django 3.2.1 on 2021-06-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profession',
            new_name='professions',
        ),
    ]
